using import.Interfaces;

namespace import.Models
{
    /// <summary>
    /// This class represents the expected JSON file.
    /// It was generated by the special paste 'Paste Json as Classes' edit option.
    /// </summary>
    internal class ProductList 
    {
        public Product[] Products { get; set; }
    }
}
